### ISSUE TITLE
Upload production ready docker image to ghcr 

### ISSUE THREAD

**Issue by uvulpos** [Clivern/Lynx#60]
Dependency for #59 

CI/CD Pipeline has to upload docker image into the ghcr so it is pullable by helm or to easy deployment without pulling the whole repo

**Comment by uvulpos** [comment]
already done

**Comment by Clivern** [comment]
You can use this image https://hub.docker.com/r/clivern/lynx/tags. it is already auto released when a new version is released https://github.com/Clivern/Lynx/blob/main/.github/workflows/docker.yml

**Comment by uvulpos** [comment]
Yeah I saw it too late. that's why I closed the issue already. The chekout confused me
