### ISSUE TITLE
Creation of Environment fails with Message status "uuid: can't be blank"

### ISSUE THREAD

**Issue by ankek** [Clivern/Lynx#64]
**Describe the bug**
Issue with creating Environment in Project. Creation of Environment always fails with Message status "uuid: can't be blank"

**Development or production environment**
Docker image: clivern/lynx:0.11.8
TF Provider version: Clivern/lynx 0.3.0

**Additional context**
Return error "uuid: can't be blank" for Web UI and Terraform provider

TF Output:
lynx_environment.prod: Creating...
╷
│ Error: Client Error
│
│   with lynx_environment.prod,
│   on main.tf line 16, in resource "lynx_environment" "prod":
│   16: resource "lynx_environment" "prod" {
│
│ Unable to create environment, got error: status: 400, body: {"errorMessage":"uuid: can't be blank"}

**Comment by Clivern** [comment]
@ankek please bump your version to v0.11.9 and check again. I was doing some refactoring in a separate brach and a change slipped into master and broke it.

**Comment by Clivern** [comment]
@ankek Please feel free to reopen the ticket if you still face the issue.

**Comment by ankek** [comment]
All works good. Thank you for fixing it
